### ISSUE TITLE
Are required fields in front end activity form working?

### ISSUE THREAD

**Issue by jcdk** [Bordr/bordr#70]
“Bug? Hm, how could this Activity go through and get published without filling in quite a few mandatory fields (name, date and CC licensing..) Did the mandatory fields get deactivated with @fepa update? ” asks @haraldssonfoto 
![image](https://cloud.githubusercontent.com/assets/1741923/23052864/9c7a6e50-f489-11e6-8ed8-d593d56f0f83.png)

**Comment by fepa** [comment]
I'm investigating this, so far I've been unable to reproduce it. Validation is working for required fields both in admin and in the frontend form. I'll do some more test runs and see if I find something.

**Comment by fepa** [comment]
I was able to reproduce it via the "Quick Edit" feature in WordPress admin. You can change the post status to Published and circumvent the unfinished fields.

![screenshot from 2017-02-17 12-21-25](https://cloud.githubusercontent.com/assets/616143/23063599/b40e15bc-f50b-11e6-8808-f11c7036a456.png)

I've made a PR to hide the link to Quick Edit: #71

This behavior is surprising, is this due to activity being a custom post type?

**Comment by fepa** [comment]
Clarification: I have still not been able to reproduce it just using the frontend form, it's not possible to save an activity when skipping required fields. I've also tested creating the activity in admin first and then trying to publish it in the frontend form.

**Comment by jcdk** [comment]
I think you're right, @fepa.  Thanks for fixing the issue on the admin site.
